name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  CPP_STANDARD: 14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{env.CPP_STANDARD}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: downloads-sorter
        path: ${{github.workspace}}/install

    - name: Run cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --inconclusive --suppress=missingIncludeSystem ${{github.workspace}}/src

    - name: Run clang-format check
      run: |
        sudo apt-get install -y clang-format
        find ${{github.workspace}}/src -name '*.cpp' -o -name '*.h' | xargs clang-format -style=file -i
        git diff --exit-code || (echo "Code style issues found. Please run clang-format locally and commit the changes." && exit 1)
